name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2️⃣ Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Test Flask import
      - name: Test Flask App
        run: python -c "import flask; print('Flask imported successfully!')"

      # 5️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t devops-app .

      # 6️⃣ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 7️⃣ Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker tag devops-app ${{ secrets.DOCKER_USERNAME }}/devops-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-app:latest
