name: CI - Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      # 1️⃣ Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

 
      # 3️⃣ Vérifier la version de Python
      - name: Check Python version
        run: |
          python3 --version
          pip3 --version

      # 4️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      # 5️⃣ Run tests
      - name: Test Flask App
        run: |
          python3 -c "import flask; print('✅ Flask imported successfully!')"
          echo "✅ All tests passed!"

      # 6️⃣ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 7️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-app:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/devops-app:latest \
                     ${{ secrets.DOCKER_USERNAME }}/devops-app:${{ github.sha }}

      # 8️⃣ Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-app:${{ github.sha }}

      # 9️⃣ Summary
      - name: Build Summary
        run: |
          echo "✅ CI Pipeline completed successfully!"
          echo "🐳 Docker image: ${{ secrets.DOCKER_USERNAME }}/devops-app:latest"
          echo "📝 Commit SHA: ${{ github.sha }}"